listenPort1 = "8081"
listenPort2 = "8082"
reactPort1 = "32777"
reactPort2 = "32778"

serverIP = "192.168.1.45"
postgresPort = "55555" 

[psql]
    host = "192.168.1.45"
    port = "55555"
    db = "postgres"
    user = "postgres"
    passwd = ""